### ISSUE TITLE
Error: Could not retrieve DB info

### ISSUE THREAD

**Issue by srinathgvelly** [PGSSoft/terraform-provider-mssql#91]
```
resource "mssql_database" "example1" {
  name      = "example1"
  collation = "SQL_Latin1_General_CP1_CS_AS"
}

resource "mssql_sql_login" "example1" {
  name     = "example1-login"
  password = "Str0ngPa$$word12"
  default_database_id = mssql_database.example1.id
  must_change_password      = false
  default_language          = "english"
  check_password_expiration = false
  check_password_policy     = false
}

resource "mssql_sql_user" "example1" {
  name        = "example1"
  database_id = mssql_database.example1.id
  login_id    = mssql_sql_login.example1.id
}

resource "mssql_database" "example2" {
  name      = "example2"
  collation = "SQL_Latin1_General_CP1_CS_AS"
}

resource "mssql_sql_login" "example2" {
  name     = "example2-login"
  password = "Str0ngPa$sword13"
  default_database_id = mssql_database.example2.id
  must_change_password      = false
  default_language          = "english"
  check_password_expiration = false
  check_password_policy     = false
}

resource "mssql_sql_user" "example2" {
  name        = "example2"
  database_id = mssql_database.example2.id
  login_id    = mssql_sql_login.example2.id
}
```
Likewise I have created for 3 more databases, logins and users.
If i do terraform apply i get this strange error

```
 Error: Could not retrieve DB info
│ 
│   with mssql_database.example1,
│   on example1.tf line 6, in resource "mssql_database" "example1":
│    6: resource "mssql_database" "example1" {
│ 
│ sql: Scan error on column index 1, name "collation_name": converting NULL
│ to string is unsupported

 Error: Could not execute SQL
│ 
│   with mssql_database.example2,
│   on example2.tf line 7, in resource "mssql_database" "example2":
│    7: resource "mssql_database" "example2" {
│ 
│ mssql: The transaction ended in the trigger. The batch has been aborted.
╵
╷
│ Error: Could not execute SQL
│ 
│   with mssql_database.example3,
│   on example3.tf line 6, in resource "mssql_database" "example3":
│    6: resource "mssql_database" "example3" {
│ 
│ mssql: The transaction ended in the trigger. The batch has been aborted.
```

FYI: I am using sql server engine version 15.00. Mssql version 0.5.0 and i also tried with 0.2.0 I got same error for both the versions. I am trying to create databases in RDS. If i connect to the RDS throught dbeaver and try to apply terraform sometime its working and sometimes i caught up with this error. This is really strange 
I am not sure what exactly is happening: can someone help me to solve this issue. I really appreciate your time.
It would be really great if someone could tackle this issue as soon as possible. 
thank you.

**Comment by Phylu** [comment]
@tkielar-pgs Is there anything, I can do to support resolving this issue? My go and mssql knowledge is questionable but I may give it a try, if you can give me some pointers and what the error may be.

**Comment by Krad-dono** [comment]
After trying multiple things I think that your issues is like mine https://github.com/PGSSoft/terraform-provider-mssql/issues/95 
In general this provider can't do any multiple db create or script block in the same apply... Somewhat stupid limitation or probably a bug. If not resolved will probably have to prod the idea to manage our rds db, users, roles and etc with terraform and move to some other solution to apply prerequisite db config.

**Comment by tkielar-pgs** [comment]
It seems to be RDS-specific limitation, where DBs cannot be created in parallel. Fix in progress...

**Comment by Krad-dono** [comment]
@tkielar-pgs , when we can expect new version of provider with this fin registry.terraform.io ?
